[package]
name = "grust-cypher-frontend"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true
[dependencies]
grust-cypher = { path = "../../../../../../crates/grust-cypher" }
grust-syntax = { path = "../../../wave-2/sketch/syntax" }
grust-functions.workspace = true
grust-unresolved-plan.workspace = true
