[workspace]
resolver = "2"
members = ["lpg", "unresolved-plan", "functions", "programmatic", "syntax", "kernel-contract"]

[workspace.package]
version = "0.2.0-draft"
edition = "2021"
publish = false
license = "Apache-2.0"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[profile.dev]
debug = 0
incremental = false

[profile.release]
debug = 0
incremental = false
