[package]
name = "grust-query-qualification"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true
[dependencies]
grust-lpg.workspace = true
grust-functions.workspace = true
grust-unresolved-plan.workspace = true
grust-resolved-plan.workspace = true
grust-optimized-plan.workspace = true
grust-resolution = { path = "../resolution" }
grust-optimizer = { path = "../optimizer" }
grust-backend = { path = "../backend" }
serde_json = "1"
grust-programmatic = {path = "../../../wave-2/sketch/programmatic"}
