[package]
name = "grust-optimizer"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true
[dependencies]
grust-lpg.workspace = true
grust-resolved-plan.workspace = true
grust-optimized-plan.workspace = true
grust-functions.workspace = true
grust-unresolved-plan.workspace = true
