# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gf/utils/v1/utils.proto
# Protobuf Python Version: 7.36.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    36,
    1,
    '',
    'gf/utils/v1/utils.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17gf/utils/v1/utils.proto\x12\x0bgf.utils.v1\"\xbe\x01\n\x07Request\x12!\n\x04ping\x18\x01 \x01(\x0b\x32\x11.gf.utils.v1.PingH\x00\x12%\n\x06\x65xists\x18\x02 \x01(\x0b\x32\x13.gf.utils.v1.ExistsH\x00\x12\x1d\n\x02ls\x18\x03 \x01(\x0b\x32\x0f.gf.utils.v1.LsH\x00\x12\x1d\n\x02rm\x18\x04 \x01(\x0b\x32\x0f.gf.utils.v1.RmH\x00\x12#\n\x05mkdir\x18\x05 \x01(\x0b\x32\x12.gf.utils.v1.MkdirH\x00\x42\x06\n\x04verb\"\x1e\n\x04Ping\x12\x16\n\x0e\x63lient_version\x18\x01 \x01(\t\"%\n\x06\x45xists\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\r\n\x05token\x18\x02 \x01(\t\"0\n\x02Ls\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\r\n\x05limit\x18\x02 \x01(\r\x12\r\n\x05token\x18\x03 \x01(\t\"!\n\x02Rm\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\r\n\x05token\x18\x02 \x01(\t\")\n\x05Mkdir\x12\x0c\n\x04root\x18\x01 \x01(\t\x12\x12\n\nrequest_id\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pyspark_pecan.utils_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUEST']._serialized_start=41
  _globals['_REQUEST']._serialized_end=231
  _globals['_PING']._serialized_start=233
  _globals['_PING']._serialized_end=263
  _globals['_EXISTS']._serialized_start=265
  _globals['_EXISTS']._serialized_end=302
  _globals['_LS']._serialized_start=304
  _globals['_LS']._serialized_end=352
  _globals['_RM']._serialized_start=354
  _globals['_RM']._serialized_end=387
  _globals['_MKDIR']._serialized_start=389
  _globals['_MKDIR']._serialized_end=430
# @@protoc_insertion_point(module_scope)
