[package]
name = "grust-postgres"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Generic PostgreSQL GraphStore backend for Grust."
keywords.workspace = true
categories.workspace = true

[dependencies]
grust-postgres-core = { version = "0.21.0", path = "../grust-postgres-core" }
